package org.bean;
// default package
// Generated Jun 20, 2016 11:51:30 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MyVehicle generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "my_vehicle", catalog = "sharemyridewebservice")
public class MyVehicle implements java.io.Serializable {

	private long myVehicleId;
	private long vehicleModelMaster;
	private long vehicleMakeMaster;
	private String vehicleNumber;
	private String style;
	private String color;
	private Integer totalSeats;
	private Date createdDate;
	private Date modifiedDate;
	private long user;

	public MyVehicle() {
	}

	public MyVehicle(long myVehicleId, long vehicleModelMaster, long vehicleMakeMaster, long user) {
		this.myVehicleId = myVehicleId;
		this.vehicleModelMaster = vehicleModelMaster;
		this.vehicleMakeMaster = vehicleMakeMaster;
		this.user = user;
	}

	public MyVehicle(long myVehicleId, long vehicleModelMaster, long vehicleMakeMaster,
			String style, String color, Integer totalSeats, Date createdDate, Date modifiedDate, long user, String vehicleNumber) {
		this.myVehicleId = myVehicleId;
		this.vehicleModelMaster = vehicleModelMaster;
		this.vehicleMakeMaster = vehicleMakeMaster;
		this.vehicleNumber = vehicleNumber;
		this.style = style;
		this.color = color;
		this.totalSeats = totalSeats;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
		this.user = user;
	}

	@Id
	@Column(name = "MY_VEHICLE_ID", unique = true, nullable = false)
	public long getMyVehicleId() {
		return this.myVehicleId;
	}

	public void setMyVehicleId(long myVehicleId) {
		this.myVehicleId = myVehicleId;
	}

	@Column(name = "VEHICLE_MODEL_ID", nullable = false)
	public long getVehicleModelMaster() {
		return this.vehicleModelMaster;
	}

	public void setVehicleModelMaster(long vehicleModelMaster) {
		this.vehicleModelMaster = vehicleModelMaster;
	}

	@Column(name = "VEHICLE_MAKE_ID", nullable = false)
	public long getVehicleMakeMaster() {
		return this.vehicleMakeMaster;
	}

	public void setVehicleMakeMaster(long vehicleMakeMaster) {
		this.vehicleMakeMaster = vehicleMakeMaster;
	}

	@Column(name = "USER_ID", nullable = false)
	public long getUser() {
		return this.user;
	}

	public void setUser(long user) {
		this.user = user;
	}

	@Column(name = "STYLE", length = 45)
	public String getStyle() {
		return this.style;
	}

	public void setStyle(String style) {
		this.style = style;
	}

	@Column(name = "VEHICLE_NUMBER", length = 45)
	public String getVehicleNumber() {
		return this.vehicleNumber;
	}

	public void setVehicleNumber(String vehicleNumber) {
		this.vehicleNumber = vehicleNumber;
	}

	@Column(name = "COLOR", length = 45)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "TOTAL_SEATS")
	public Integer getTotalSeats() {
		return this.totalSeats;
	}

	public void setTotalSeats(Integer totalSeats) {
		this.totalSeats = totalSeats;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFIED_DATE", length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
