package org.bean;
// default package
// Generated Jul 18, 2016 4:06:33 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * OfferedRide generated by hbm2java
 */

@SuppressWarnings("serial")
public class OfferedRide implements java.io.Serializable {
	
	@Id
	@Column(name="OFFERED_RIDE_ID")
	@GeneratedValue 
	private Long offeredRideId;
	private long myVehicle;
	private long user;
	private String fromLocation;
	private String toLocation;
	private Date startDatetime;
	private Byte isRoundTrip;
	private Date returnDatetime;
	private Byte luggage;
	private Byte offeredSeats;
	private Byte preferredGender;
	private Byte timeAdjustment;
	private Byte detour;
	private Byte PICK_UP_FLEXIBILITY;
	private String LANGUAGE;
	private Byte PET;
	private Date CREATED_DATE;
	private Date MODIFIED_DATE;


	public OfferedRide() {
	}

	public OfferedRide(Long offeredRideId, long user, String fromLocation, String toLocation) {
		this.offeredRideId = offeredRideId;
		this.user = user;
		this.fromLocation = fromLocation;
		this.toLocation = toLocation;
	}

	public OfferedRide(Long offeredRideId, long myVehicle, long user, String fromLocation, String toLocation,
			Date startDatetime, Byte isRoundTrip, Date returnDatetime, Byte luggage, Byte offeredSeats,
			Byte preferredGender, Byte timeAdjustment, Byte detour, Byte PICK_UP_FLEXIBILITY, String LANGUAGE, 
			Byte PET, Date CREATED_DATE, Date MODIFIED_DATE) {
		this.offeredRideId = offeredRideId;
		this.myVehicle = myVehicle;
		this.user = user;
		this.fromLocation = fromLocation;
		this.toLocation = toLocation;
		this.startDatetime = startDatetime;
		this.isRoundTrip = isRoundTrip;
		this.returnDatetime = returnDatetime;
		this.luggage = luggage;
		this.offeredSeats = offeredSeats;
		this.preferredGender = preferredGender;
		this.timeAdjustment = timeAdjustment;
		this.detour = detour;
		this.PICK_UP_FLEXIBILITY = PICK_UP_FLEXIBILITY;
		this.LANGUAGE = LANGUAGE;
		this.PET = PET;
		this.CREATED_DATE = CREATED_DATE;
		this.MODIFIED_DATE = MODIFIED_DATE;
	}

	
	public Long getOfferedRideId() {
		return this.offeredRideId;
	}

	public void setOfferedRideId(Long offeredRideId) {
		this.offeredRideId = offeredRideId;
	}


	public long getMyVehicle() {
		return this.myVehicle;
	}

	public void setMyVehicle(long myVehicle) {
		this.myVehicle = myVehicle;
	}


	public long getUser() {
		return this.user;
	}

	public void setUser(long user) {
		this.user = user;
	}


	public String getFromLocation() {
		return this.fromLocation;
	}

	public void setFromLocation(String fromLocation) {
		this.fromLocation = fromLocation;
	}


	public String getToLocation() {
		return this.toLocation;
	}

	public void setToLocation(String toLocation) {
		this.toLocation = toLocation;
	}


	public Date getStartDatetime() {
		return this.startDatetime;
	}

	public void setStartDatetime(Date startDatetime) {
		this.startDatetime = startDatetime;
	}

	
	public Byte getIsRoundTrip() {
		return this.isRoundTrip;
	}

	public void setIsRoundTrip(Byte isRoundTrip) {
		this.isRoundTrip = isRoundTrip;
	}


	public Date getReturnDatetime() {
		return this.returnDatetime;
	}

	public void setReturnDatetime(Date returnDatetime) {
		this.returnDatetime = returnDatetime;
	}

	
	public Byte getLuggage() {
		return this.luggage;
	}

	public void setLuggage(Byte luggage) {
		this.luggage = luggage;
	}

	public Byte getOfferedSeats() {
		return this.offeredSeats;
	}

	public void setOfferedSeats(Byte offeredSeats) {
		this.offeredSeats = offeredSeats;
	}

	
	public Byte getPreferredGender() {
		return this.preferredGender;
	}

	public void setPreferredGender(Byte preferredGender) {
		this.preferredGender = preferredGender;
	}


	public Byte getTimeAdjustment() {
		return this.timeAdjustment;
	}

	public void setTimeAdjustment(Byte timeAdjustment) {
		this.timeAdjustment = timeAdjustment;
	}

	
	public Byte getPICK_UP_FLEXIBILITY() {
		return this.PICK_UP_FLEXIBILITY;
	}

	public void setPICK_UP_FLEXIBILITY(Byte PICK_UP_FLEXIBILITY) {
		this.PICK_UP_FLEXIBILITY = PICK_UP_FLEXIBILITY;
	}


	public Byte getPET() {
		return this.PET;
	}

	public void setPET(Byte PET) {
		this.PET = PET;
	}

	public String getLanguage() {
		return this.LANGUAGE;
	}

	public void setLanguage(String LANGUAGE) {
		this.LANGUAGE = LANGUAGE;
	}

	public Date getCreatedDate() {
		return this.CREATED_DATE;
	}

	public void setCreatedDate(Date CREATED_DATE) {
		this.CREATED_DATE = CREATED_DATE;
	}

	public Date getModifiedDate() {
		return this.MODIFIED_DATE;
	}

	public void setModifiedDate(Date MODIFIED_DATE) {
		this.MODIFIED_DATE = MODIFIED_DATE;
	}



	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("OfferedRide [offeredRideId=");
		builder.append(offeredRideId);
		builder.append(", myVehicle=");
		builder.append(myVehicle);
		builder.append(", user=");
		builder.append(user);
		builder.append(", fromLocation=");
		builder.append(fromLocation);
		builder.append(", toLocation=");
		builder.append(toLocation);
		builder.append(", startDatetime=");
		builder.append(startDatetime);
		builder.append(", isRoundTrip=");
		builder.append(isRoundTrip);
		builder.append(", returnDatetime=");
		builder.append(returnDatetime);
		builder.append(", luggage=");
		builder.append(luggage);
		builder.append(", offeredSeats=");
		builder.append(offeredSeats);
		builder.append(", preferredGender=");
		builder.append(preferredGender);
		builder.append(", timeAdjustment=");
		builder.append(timeAdjustment);
		builder.append(", detour=");
		builder.append(detour);
		builder.append("]");
		return builder.toString();
	}

}





