package org.bean;
// default package
// Generated Jul 18, 2016 4:06:33 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OfferedRide generated by hbm2java
 */
@Entity
@Table(name = "offered_ride", catalog = "sharemyridewebservice")
public class OfferedRide implements java.io.Serializable {

	private long offeredRideId;
	private MyVehicle myVehicle;
	private User user;
	private String fromLocation;
	private String toLocation;
	private Date startDatetime;
	private Byte isRoundTrip;
	private Date returnDatetime;
	private Byte luggage;
	private Byte offeredSeats;
	private Byte preferredGender;
	private Byte timeAdjustment;
	private Byte detour;

	public OfferedRide() {
	}

	public OfferedRide(long offeredRideId, User user, String fromLocation, String toLocation) {
		this.offeredRideId = offeredRideId;
		this.user = user;
		this.fromLocation = fromLocation;
		this.toLocation = toLocation;
	}

	public OfferedRide(long offeredRideId, MyVehicle myVehicle, User user, String fromLocation, String toLocation,
			Date startDatetime, Byte isRoundTrip, Date returnDatetime, Byte luggage, Byte offeredSeats,
			Byte preferredGender, Byte timeAdjustment, Byte detour) {
		this.offeredRideId = offeredRideId;
		this.myVehicle = myVehicle;
		this.user = user;
		this.fromLocation = fromLocation;
		this.toLocation = toLocation;
		this.startDatetime = startDatetime;
		this.isRoundTrip = isRoundTrip;
		this.returnDatetime = returnDatetime;
		this.luggage = luggage;
		this.offeredSeats = offeredSeats;
		this.preferredGender = preferredGender;
		this.timeAdjustment = timeAdjustment;
		this.detour = detour;
	}

	@Id

	@Column(name = "OFFERED_RIDE_ID", unique = true, nullable = false)
	public long getOfferedRideId() {
		return this.offeredRideId;
	}

	public void setOfferedRideId(long offeredRideId) {
		this.offeredRideId = offeredRideId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MY_VEHICLE_ID")
	public MyVehicle getMyVehicle() {
		return this.myVehicle;
	}

	public void setMyVehicle(MyVehicle myVehicle) {
		this.myVehicle = myVehicle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "FROM_LOCATION", nullable = false, length = 100)
	public String getFromLocation() {
		return this.fromLocation;
	}

	public void setFromLocation(String fromLocation) {
		this.fromLocation = fromLocation;
	}

	@Column(name = "TO_LOCATION", nullable = false, length = 100)
	public String getToLocation() {
		return this.toLocation;
	}

	public void setToLocation(String toLocation) {
		this.toLocation = toLocation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_DATETIME", length = 19)
	public Date getStartDatetime() {
		return this.startDatetime;
	}

	public void setStartDatetime(Date startDatetime) {
		this.startDatetime = startDatetime;
	}

	@Column(name = "IS_ROUND_TRIP")
	public Byte getIsRoundTrip() {
		return this.isRoundTrip;
	}

	public void setIsRoundTrip(Byte isRoundTrip) {
		this.isRoundTrip = isRoundTrip;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RETURN_DATETIME", length = 19)
	public Date getReturnDatetime() {
		return this.returnDatetime;
	}

	public void setReturnDatetime(Date returnDatetime) {
		this.returnDatetime = returnDatetime;
	}

	@Column(name = "LUGGAGE")
	public Byte getLuggage() {
		return this.luggage;
	}

	public void setLuggage(Byte luggage) {
		this.luggage = luggage;
	}

	@Column(name = "OFFERED_SEATS")
	public Byte getOfferedSeats() {
		return this.offeredSeats;
	}

	public void setOfferedSeats(Byte offeredSeats) {
		this.offeredSeats = offeredSeats;
	}

	@Column(name = "PREFERRED_GENDER")
	public Byte getPreferredGender() {
		return this.preferredGender;
	}

	public void setPreferredGender(Byte preferredGender) {
		this.preferredGender = preferredGender;
	}

	@Column(name = "TIME_ADJUSTMENT")
	public Byte getTimeAdjustment() {
		return this.timeAdjustment;
	}

	public void setTimeAdjustment(Byte timeAdjustment) {
		this.timeAdjustment = timeAdjustment;
	}

	@Column(name = "DETOUR")
	public Byte getDetour() {
		return this.detour;
	}

	public void setDetour(Byte detour) {
		this.detour = detour;
	}

}
