package org.bean;
// default package
// Generated Jul 18, 2016 4:06:33 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * OfferedRide generated by hbm2java
 */

public class OfferedRide implements java.io.Serializable {
	
	@Id
	@Column(name="OFFERED_RIDE_ID")
	@GeneratedValue 
	private Long offeredRideId;
	private Long myVehicle;
	private Long user;
	private String fromLocation;
	private String toLocation;
	private Date startDatetime;
	private Byte isRoundTrip;
	private Date returnDatetime;
	private Byte luggage;
	private Byte offeredSeats;
	private Byte preferredGender;
	private Byte timeAdjustment;
	private Byte detour;

	public OfferedRide() {
	}

	public OfferedRide(Long offeredRideId, Long user, String fromLocation, String toLocation) {
		this.offeredRideId = offeredRideId;
		this.user = user;
		this.fromLocation = fromLocation;
		this.toLocation = toLocation;
	}

	public OfferedRide(Long offeredRideId, Long myVehicle, Long user, String fromLocation, String toLocation,
			Date startDatetime, Byte isRoundTrip, Date returnDatetime, Byte luggage, Byte offeredSeats,
			Byte preferredGender, Byte timeAdjustment, Byte detour) {
		this.offeredRideId = offeredRideId;
		this.myVehicle = myVehicle;
		this.user = user;
		this.fromLocation = fromLocation;
		this.toLocation = toLocation;
		this.startDatetime = startDatetime;
		this.isRoundTrip = isRoundTrip;
		this.returnDatetime = returnDatetime;
		this.luggage = luggage;
		this.offeredSeats = offeredSeats;
		this.preferredGender = preferredGender;
		this.timeAdjustment = timeAdjustment;
		this.detour = detour;
	}

	
	public Long getOfferedRideId() {
		return this.offeredRideId;
	}

	public void setOfferedRideId(Long offeredRideId) {
		this.offeredRideId = offeredRideId;
	}


	public Long getMyVehicle() {
		return this.myVehicle;
	}

	public void setMyVehicle(Long myVehicle) {
		this.myVehicle = myVehicle;
	}


	public Long getUser() {
		return this.user;
	}

	public void setUser(Long user) {
		this.user = user;
	}


	public String getFromLocation() {
		return this.fromLocation;
	}

	public void setFromLocation(String fromLocation) {
		this.fromLocation = fromLocation;
	}


	public String getToLocation() {
		return this.toLocation;
	}

	public void setToLocation(String toLocation) {
		this.toLocation = toLocation;
	}


	public Date getStartDatetime() {
		return this.startDatetime;
	}

	public void setStartDatetime(Date startDatetime) {
		this.startDatetime = startDatetime;
	}

	
	public Byte getIsRoundTrip() {
		return this.isRoundTrip;
	}

	public void setIsRoundTrip(Byte isRoundTrip) {
		this.isRoundTrip = isRoundTrip;
	}


	public Date getReturnDatetime() {
		return this.returnDatetime;
	}

	public void setReturnDatetime(Date returnDatetime) {
		this.returnDatetime = returnDatetime;
	}

	
	public Byte getLuggage() {
		return this.luggage;
	}

	public void setLuggage(Byte luggage) {
		this.luggage = luggage;
	}

	public Byte getOfferedSeats() {
		return this.offeredSeats;
	}

	public void setOfferedSeats(Byte offeredSeats) {
		this.offeredSeats = offeredSeats;
	}

	
	public Byte getPreferredGender() {
		return this.preferredGender;
	}

	public void setPreferredGender(Byte preferredGender) {
		this.preferredGender = preferredGender;
	}


	public Byte getTimeAdjustment() {
		return this.timeAdjustment;
	}

	public void setTimeAdjustment(Byte timeAdjustment) {
		this.timeAdjustment = timeAdjustment;
	}

	
	public Byte getDetour() {
		return this.detour;
	}

	public void setDetour(Byte detour) {
		this.detour = detour;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("OfferedRide [offeredRideId=");
		builder.append(offeredRideId);
		builder.append(", myVehicle=");
		builder.append(myVehicle);
		builder.append(", user=");
		builder.append(user);
		builder.append(", fromLocation=");
		builder.append(fromLocation);
		builder.append(", toLocation=");
		builder.append(toLocation);
		builder.append(", startDatetime=");
		builder.append(startDatetime);
		builder.append(", isRoundTrip=");
		builder.append(isRoundTrip);
		builder.append(", returnDatetime=");
		builder.append(returnDatetime);
		builder.append(", luggage=");
		builder.append(luggage);
		builder.append(", offeredSeats=");
		builder.append(offeredSeats);
		builder.append(", preferredGender=");
		builder.append(preferredGender);
		builder.append(", timeAdjustment=");
		builder.append(timeAdjustment);
		builder.append(", detour=");
		builder.append(detour);
		builder.append("]");
		return builder.toString();
	}

}





