package org.bean; 
// Generated May 21, 2016 9:47:31 PM by Hibernate Tools 5.0.0.Alpha3

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="user")
public class User implements java.io.Serializable {

	
	@Id
	@Column(name="USER_ID")
	@GeneratedValue 
	private Long userId;
	
	private String firstname;
	private String lastname;
	private String gender;
	private String email;
	private String password;
	private String facebookId;
	private String googleId;
	private String twitterId;
	private Date birthdate;
	private String contact;
	private String address1;
	private String address2;
	private String city;
	private String state;
	private String country;
	private Date created;
	private String createdBy;
	private Date modified;
	private String modifiedBy;
	private boolean isAuthorized;
	private String validToken;

	public User() {
	}

	public User(Date created, Date modified) {
		this.created = created;
		this.modified = modified;
	}

	public User(String firstname, String lastname, String gender, String email, String password, String facebookId,
			String googleId, String twitterId, Date birthdate, String contact, String address1, String address2,
			String city, String state, String country, Date created, String createdBy, Date modified,
			String modifiedBy, boolean isAuthorized, String validToken) {
		this.firstname = firstname;
		this.lastname = lastname;
		this.gender = gender;
		this.email = email;
		this.password = password;
		this.facebookId = facebookId;
		this.googleId = googleId;
		this.twitterId = twitterId;
		this.birthdate = birthdate;
		this.contact = contact;
		this.address1 = address1;
		this.address2 = address2;
		this.city = city;
		this.state = state;
		this.country = country;
		this.created = created;
		this.createdBy = createdBy;
		this.modified = modified;
		this.modifiedBy = modifiedBy;
		this.isAuthorized = isAuthorized;
		this.validToken = validToken;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFacebookId() {
		return this.facebookId;
	}

	public void setFacebookId(String facebookId) {
		this.facebookId = facebookId;
	}

	public String getGoogleId() {
		return this.googleId;
	}

	public void setGoogleId(String googleId) {
		this.googleId = googleId;
	}

	public String getTwitterId() {
		return this.twitterId;
	}

	public void setTwitterId(String twitterId) {
		this.twitterId = twitterId;
	}

	public Date getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public boolean getIsAuthorized() {
		return this.isAuthorized;
	}

	public void setIsAuthorized(boolean isAuthorized) {
		this.isAuthorized = isAuthorized;
	}

	public String getValidToken() {
		return this.validToken;
	}

	public void setValidToken(String validToken) {
		this.validToken = validToken;
	}		
}
