package org.bean;
// Generated Jun 1, 2016 6:31:42 PM by Hibernate Tools 3.5.0.Final


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VehicleMakeMaster generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="vehicle_make_master")
public class VehicleMakeMaster implements java.io.Serializable {

	
	@Id
	@Column(name="VEHICLE_ID")
	@GeneratedValue 
	private Long vehicleId;
	private String receivedVehicleId;
	private String name;
	private String niceName;
	private Date created;
	private String createdBy;
	private Date modified;
	private String modifiedBy;
/*	private Set<VehicleModelMaster> vehicleModelMastersForVehicleId = new HashSet<VehicleModelMaster>(0);
	private Set<VehicleModelMaster> vehicleModelMastersForReceivedVehicleId = new HashSet<VehicleModelMaster>(0);
*/
	public VehicleMakeMaster() {
	}

	public VehicleMakeMaster(String receivedVehicleId, Date created, Date modified) {
		this.receivedVehicleId = receivedVehicleId;
		this.created = created;
		this.modified = modified;
	}

	public VehicleMakeMaster(String receivedVehicleId, String name, String niceName, Date created, String createdBy,
			Date modified, String modifiedBy/*, Set<VehicleModelMaster> vehicleModelMastersForVehicleId,
			Set<VehicleModelMaster> vehicleModelMastersForReceivedVehicleId */) {
		this.receivedVehicleId = receivedVehicleId;
		this.name = name;
		this.niceName = niceName;
		this.created = created;
		this.createdBy = createdBy;
		this.modified = modified;
		this.modifiedBy = modifiedBy;
	//	this.vehicleModelMastersForVehicleId = vehicleModelMastersForVehicleId;
	//	this.vehicleModelMastersForReceivedVehicleId = vehicleModelMastersForReceivedVehicleId; 
	}

	public Long getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(Long vehicleId) {
		this.vehicleId = vehicleId;
	}

	public String getReceivedVehicleId() {
		return this.receivedVehicleId;
	}

	public void setReceivedVehicleId(String receivedVehicleId) {
		this.receivedVehicleId = receivedVehicleId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNiceName() {
		return this.niceName;
	}

	public void setNiceName(String niceName) {
		this.niceName = niceName;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

/*	public Set<VehicleModelMaster> getVehicleModelMastersForVehicleId() {
		return this.vehicleModelMastersForVehicleId;
	}

	public void setVehicleModelMastersForVehicleId(Set<VehicleModelMaster> vehicleModelMastersForVehicleId) {
		this.vehicleModelMastersForVehicleId = vehicleModelMastersForVehicleId;
	}

	public Set<VehicleModelMaster> getVehicleModelMastersForReceivedVehicleId() {
		return this.vehicleModelMastersForReceivedVehicleId;
	}

	public void setVehicleModelMastersForReceivedVehicleId(
			Set<VehicleModelMaster> vehicleModelMastersForReceivedVehicleId) {
		this.vehicleModelMastersForReceivedVehicleId = vehicleModelMastersForReceivedVehicleId;
	}
*/
}
