package org.bean;
// Generated Jun 1, 2016 6:31:42 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * VehicleModelMaster generated by HeerHirpara
 */

@SuppressWarnings("serial")
@Entity
@Table(name="vehicle_model_master")
public class VehicleModelMaster implements java.io.Serializable {

	/**
	 * 
	 */
	
	@Id
	@Column(name="MODEL_ID")
	@GeneratedValue 
	private Long modelId;
	
/*	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
        @JoinColumn(name = "VEHICLE_ID", referencedColumnName = "VEHICLE_ID"),
        @JoinColumn(name = "RECEIVED_VEHICLE_ID", referencedColumnName = "RECEIVED_VEHICLE_ID")
    })
*/	
	
	@Column(name = "VEHICLE_ID")
	private long vehicleMakeMasterByVehicleId;
	
	@Column(name = "RECEIVED_VEHICLE_ID")
	private String vehicleMakeMasterByReceivedVehicleId;
	
	private String modelName;
	private String modelCode;
	private String receivedModelId;
	private String createdBy;
	private Date created;
	private String modifiedBy;
	private Date modified;

	public VehicleModelMaster() {
	}

	public VehicleModelMaster(String modelName, String modelCode, String receivedModelId) {
		this.modelName = modelName;
		this.modelCode = modelCode;
		this.receivedModelId = receivedModelId;
	}

	public VehicleModelMaster(long vehicleMakeMasterByVehicleId,
			String modelName, String modelCode,
			String receivedModelId, String createdBy, Date created, String modifiedBy, Date modified, String vehicleMakeMasterByReceivedVehicleId) {
		this.vehicleMakeMasterByVehicleId = vehicleMakeMasterByVehicleId;
		this.vehicleMakeMasterByReceivedVehicleId = vehicleMakeMasterByReceivedVehicleId;
		this.modelName = modelName;
		this.modelCode = modelCode;
		this.receivedModelId = receivedModelId;
		this.createdBy = createdBy;
		this.created = created;
		this.modifiedBy = modifiedBy;
		this.modified = modified;
	}

	public Long getModelId() {
		return this.modelId;
	}

	public void setModelId(Long modelId) {
		this.modelId = modelId;
	}

	public long getVehicleMakeMasterByVehicleId() {
		return this.vehicleMakeMasterByVehicleId;
	}

	public void setVehicleMakeMasterByVehicleId(long vehicleMakeMasterByVehicleId) {
		this.vehicleMakeMasterByVehicleId = vehicleMakeMasterByVehicleId;
	}

	public String getVehicleMakeMasterByReceivedVehicleId() {
		return this.vehicleMakeMasterByReceivedVehicleId;
	}

	public void setVehicleMakeMasterByReceivedVehicleId(String vehicleMakeMasterByReceivedVehicleId) {
		this.vehicleMakeMasterByReceivedVehicleId = vehicleMakeMasterByReceivedVehicleId;
	}
	
	
	public String getModelName() {
		return this.modelName;
	}

	public void setModelName(String modelName) {
		this.modelName = modelName;
	}

	public String getModelCode() {
		return this.modelCode;
	}

	public void setModelCode(String modelCode) {
		this.modelCode = modelCode;
	}

	public String getReceivedModelId() {
		return this.receivedModelId;
	}

	public void setReceivedModelId(String receivedModelId) {
		this.receivedModelId = receivedModelId;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

}
