CREATE TABLE `sharemyridewebservice`.`my_vehicle` (
  `MY_VEHICLE_ID` BIGINT(20) NOT NULL,
  `VEHICLE_MAKE_ID` BIGINT(20) NOT NULL,
  `VEHICLE_MODEL_ID` BIGINT(20) NOT NULL,
  `STYLE` VARCHAR(45) NULL,
  `COLOR` VARCHAR(45) NULL,
  `TOTAL_SEATS` INT NULL,
  `CREATED_DATE` TIMESTAMP NULL,
  `MODIFIED_DATE` TIMESTAMP NULL,
  PRIMARY KEY (`MY_VEHICLE_ID`));

  ALTER TABLE `sharemyridewebservice`.`my_vehicle` 
ADD CONSTRAINT `VEHICLE_MAKE_ID`
  FOREIGN KEY (`VEHICLE_MAKE_ID`)
  REFERENCES `sharemyridewebservice`.`vehicle_make_master` (`VEHICLE_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `VEHICLE_MODEL_ID`
  FOREIGN KEY (`VEHICLE_MODEL_ID`)
  REFERENCES `sharemyridewebservice`.`vehicle_model_master` (`MODEL_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

  ALTER TABLE `sharemyridewebservice`.`my_vehicle` 
ADD COLUMN `USER_ID` BIGINT(20) NOT NULL AFTER `MODIFIED_DATE`,
ADD INDEX `USER_ID_idx` (`USER_ID` ASC);
ALTER TABLE `sharemyridewebservice`.`my_vehicle` 
ADD CONSTRAINT `USER_ID`
  FOREIGN KEY (`USER_ID`)
  REFERENCES `sharemyridewebservice`.`user` (`USER_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
  
  ALTER TABLE `sharemyridewebservice`.`my_vehicle` 
ADD COLUMN `VEHICLE_NUMBER` VARCHAR(45) NOT NULL AFTER `USER_ID`;
