CREATE TABLE USER
(
USER_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
FIRSTNAME VARCHAR(30),
LASTNAME VARCHAR(30),
GENDER VARCHAR(1),
EMAIL VARCHAR(30),
PASSWORD VARCHAR(30),
FACEBOOK_ID VARCHAR(35),
GOOGLE_ID VARCHAR(35),
TWITTER_ID VARCHAR(35),
BIRTHDATE TIME,
CONTACT VARCHAR(30),
ADDRESS1 VARCHAR(30),
ADDRESS2 VARCHAR(30),
CITY VARCHAR(30),
STATE VARCHAR(30),
COUNTRY VARCHAR(30),
CREATED TIMESTAMP DEFAULT NOW(),
CREATED_BY	VARCHAR(30),
MODIFIED TIMESTAMP DEFAULT NOW(),
MODIFIED_BY VARCHAR(30)
);

ALTER TABLE `sharemyridewebservice`.`user` 
ADD COLUMN `IS_AUTHOROZED` TINYINT NULL AFTER `MODIFIED_BY`,
ADD COLUMN `VALID_TOKEN` VARCHAR(45) NULL AFTER `IS_AUTHOROZED`;
