CREATE TABLE USER
(
VEHICLE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
MAKE VARCHAR(30),
MODEL VARCHAR(30),
CREATED TIMESTAMP DEFAULT NOW(),
CREATED_BY	VARCHAR(30),
MODIFIED TIMESTAMP DEFAULT NOW(),
MODIFIED_BY VARCHAR(30)
);