/*CREATE TABLE `sharemyridewebservice`.`vehicle_model_master` (
  `MODEL_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `MODEL_NAME` VARCHAR(45) NOT NULL,
  `MODEL_CODE` VARCHAR(30) NOT NULL,
  `RECEIVED_MODEL_ID` VARCHAR(30) NOT NULL,
  `CREATED_BY` VARCHAR(30) NULL,
  `CREATED` TIMESTAMP NULL DEFAULT now(),
  `MODIFIED_BY` VARCHAR(30) NULL,
  `MODIFIED` TIMESTAMP NULL DEFAULT now(),
  `RECEIVED_VEHICLE_ID` VARCHAR(30) NULL,
  `VEHICLE_ID` BIGINT NULL,
  PRIMARY KEY (`MODEL_ID`),
  INDEX `VEHICLE_ID_idx` (`VEHICLE_ID` ASC),
  CONSTRAINT `VEHICLE_ID`
    FOREIGN KEY (`VEHICLE_ID`)
    REFERENCES `sharemyridewebservice`.`vehicle_make_master` (`VEHICLE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    )
COMMENT = 'LIST OF MODELS FOR AVAILABLE MAKE/BRAND';


ALTER TABLE `sharemyridewebservice`.`vehicle_model_master` 
CHANGE COLUMN `RECEIVED_MODEL_ID` `RECEIVED_MODEL_ID` VARCHAR(80) NOT NULL ;


CREATE TABLE `vehicle_model_master` (
  `MODEL_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MODEL_NAME` varchar(45) NOT NULL,
  `MODEL_CODE` varchar(30) NOT NULL,
  `RECEIVED_MODEL_ID` varchar(80) NOT NULL,
  `CREATED_BY` varchar(30) DEFAULT NULL,
  `CREATED` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(30) DEFAULT NULL,
  `MODIFIED` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `RECEIVED_VEHICLE_ID` varchar(30) DEFAULT NULL,
  `VEHICLE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`MODEL_ID`),
  KEY `RECEIVED_VEHICLE_ID_idx` (`RECEIVED_VEHICLE_ID`),
  KEY `VEHICLE_ID_idx` (`VEHICLE_ID`),
  CONSTRAINT `VEHICLE_ID` FOREIGN KEY (`VEHICLE_ID`) REFERENCES `vehicle_make_master` (`VEHICLE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `RECEIVED_VEHICLE_ID` FOREIGN KEY (`RECEIVED_VEHICLE_ID`) REFERENCES `vehicle_make_master` (`RECEIVED_VEHICLE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=121 DEFAULT CHARSET=latin1 COMMENT='LIST OF MODELS FOR AVAILABLE MAKE/BRAND'
*/

CREATE TABLE `vehicle_model_master` (
  `MODEL_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MODEL_NAME` varchar(80) NOT NULL,
  `MODEL_CODE` varchar(80) NOT NULL,
  `RECEIVED_MODEL_ID` varchar(80) NOT NULL,
  `CREATED_BY` varchar(30) DEFAULT NULL,
  `CREATED` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(30) DEFAULT NULL,
  `MODIFIED` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `RECEIVED_VEHICLE_ID` varchar(30) DEFAULT NULL,
  `VEHICLE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`MODEL_ID`),
  KEY `RECEIVED_VEHICLE_ID_idx` (`RECEIVED_VEHICLE_ID`),
  KEY `VEHICLE_ID_idx` (`VEHICLE_ID`),
  CONSTRAINT `VEHICLE_ID` FOREIGN KEY (`VEHICLE_ID`) REFERENCES `vehicle_make_master` (`VEHICLE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `RECEIVED_VEHICLE_ID` FOREIGN KEY (`RECEIVED_VEHICLE_ID`) REFERENCES `vehicle_make_master` (`RECEIVED_VEHICLE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1484 DEFAULT CHARSET=latin1 COMMENT='LIST OF MODELS FOR AVAILABLE MAKE/BRAND'