CREATE TABLE `sharemyridewebservice`.`vehicle_model_master` (
  `MODEL_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `MODEL_NAME` VARCHAR(45) NOT NULL,
  `MODEL_CODE` VARCHAR(30) NOT NULL,
  `RECEIVED_MODEL_ID` VARCHAR(30) NOT NULL,
  `CREATED_BY` VARCHAR(30) NULL,
  `CREATED` TIMESTAMP NULL DEFAULT now(),
  `MODIFIED_BY` VARCHAR(30) NULL,
  `MODIFIED` TIMESTAMP NULL DEFAULT now(),
  `RECEIVED_VEHICLE_ID` VARCHAR(30) NULL,
  `VEHICLE_ID` BIGINT NULL,
  PRIMARY KEY (`MODEL_ID`),
  INDEX `VEHICLE_ID_idx` (`VEHICLE_ID` ASC),
  CONSTRAINT `VEHICLE_ID`
    FOREIGN KEY (`VEHICLE_ID`)
    REFERENCES `sharemyridewebservice`.`vehicle_make_master` (`VEHICLE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    )
COMMENT = 'LIST OF MODELS FOR AVAILABLE MAKE/BRAND';


