CREATE TABLE VEHICLE_MAKE_MASTER
(
VEHICLE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
RECEIVED_VEHICLE_ID VARCHAR(30),
NAME VARCHAR(30),
NICE_NAME VARCHAR(30),
CREATED TIMESTAMP DEFAULT NOW(),
CREATED_BY	VARCHAR(30),
MODIFIED TIMESTAMP DEFAULT NOW(),
MODIFIED_BY VARCHAR(30)
);


ALTER TABLE `sharemyridewebservice`.`vehicle_make_master` 
CHANGE COLUMN `RECEIVED_VEHICLE_ID` `RECEIVED_VEHICLE_ID` VARCHAR(30) NOT NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`VEHICLE_ID`, `RECEIVED_VEHICLE_ID`);
