/*CREATE TABLE VEHICLE_MAKE_MASTER
(
VEHICLE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
RECEIVED_VEHICLE_ID VARCHAR(30),
NAME VARCHAR(30),
NICE_NAME VARCHAR(30),
CREATED TIMESTAMP DEFAULT NOW(),
CREATED_BY	VARCHAR(30),
MODIFIED TIMESTAMP DEFAULT NOW(),
MODIFIED_BY VARCHAR(30)
);


ALTER TABLE `sharemyridewebservice`.`vehicle_make_master` 
CHANGE COLUMN `RECEIVED_VEHICLE_ID` `RECEIVED_VEHICLE_ID` VARCHAR(30) NOT NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`VEHICLE_ID`, `RECEIVED_VEHICLE_ID`);


ALTER TABLE `sharemyridewebservice`.`vehicle_make_master` 
CHANGE COLUMN `RECEIVED_VEHICLE_ID` `RECEIVED_VEHICLE_ID` VARCHAR(80) NOT NULL ;
*/

CREATE TABLE `vehicle_make_master` (
  `VEHICLE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `RECEIVED_VEHICLE_ID` varchar(80) NOT NULL,
  `NAME` varchar(50) DEFAULT NULL,
  `NICE_NAME` varchar(50) DEFAULT NULL,
  `CREATED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(30) DEFAULT NULL,
  `MODIFIED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`VEHICLE_ID`),
  UNIQUE KEY `RECEIVED_VEHICLE_ID_UNIQUE` (`RECEIVED_VEHICLE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=91 DEFAULT CHARSET=latin1
